import type { Package, Testimonial, FAQ } from "./types"

export const corporatePackages: Package[] = [
  {
    id: "corp-1",
    category: "corporativo",
    title: "Incentivo Miami Premium",
    destination: "Miami, USA",
    nights: 4,
    priceFrom: 2500,
    highlights: [
      "Hotel 5 estrellas en South Beach",
      "Sala de reuniones equipada",
      "Team building en yate privado",
      "Cena de gala incluida",
    ],
    image: "/images/corp-miami.jpg",
    badge: "Top",
    includes: {
      flight: true,
      hotel: true,
      transfers: true,
      insurance: true,
      meals: true,
    },
    description: "Experiencia premium para equipos de alto rendimiento",
  },
  {
    id: "corp-2",
    category: "corporativo",
    title: "Congreso Barcelona",
    destination: "Barcelona, España",
    nights: 5,
    priceFrom: 3200,
    highlights: ["Hotel céntrico 4 estrellas", "Centro de convenciones", "Traducción simultánea", "Networking events"],
    image: "/images/corp-barcelona.jpg",
    badge: "Nuevo",
    includes: {
      flight: true,
      hotel: true,
      transfers: true,
      insurance: true,
    },
  },
  {
    id: "corp-3",
    category: "corporativo",
    title: "Retiro Ejecutivo Mendoza",
    destination: "Mendoza, Argentina",
    nights: 3,
    priceFrom: 1800,
    highlights: [
      "Lodge boutique en viñedos",
      "Salas de estrategia privadas",
      "Experiencias enológicas",
      "Actividades outdoor",
    ],
    image: "/images/corp-mendoza.jpg",
    includes: {
      flight: true,
      hotel: true,
      transfers: true,
      insurance: true,
      meals: true,
      activities: true,
    },
  },
  {
    id: "corp-4",
    category: "corporativo",
    title: "Feria Tech Dubai",
    destination: "Dubai, UAE",
    nights: 6,
    priceFrom: 4500,
    highlights: ["Hotel 5 estrellas Downtown", "Pases VIP a expo", "Business lounge access", "City tour ejecutivo"],
    image: "/images/corp-dubai.jpg",
    badge: "Promo",
    includes: {
      flight: true,
      hotel: true,
      transfers: true,
      insurance: true,
    },
  },
  {
    id: "corp-5",
    category: "corporativo",
    title: "Capacitación Cancún",
    destination: "Cancún, México",
    nights: 4,
    priceFrom: 2100,
    highlights: ["Resort all-inclusive", "Salas de capacitación", "Actividades de integración", "Playa privada"],
    image: "/images/corp-cancun.jpg",
    includes: {
      flight: true,
      hotel: true,
      transfers: true,
      insurance: true,
      meals: true,
    },
  },
  {
    id: "corp-6",
    category: "corporativo",
    title: "Summit Santiago",
    destination: "Santiago, Chile",
    nights: 3,
    priceFrom: 1600,
    highlights: ["Hotel corporativo premium", "Centro de negocios", "Catering ejecutivo", "Tour Valle Nevado"],
    image: "/images/corp-santiago.jpg",
    includes: {
      flight: true,
      hotel: true,
      transfers: true,
      insurance: true,
    },
  },
  {
    id: "corp-7",
    category: "corporativo",
    title: "Incentivo Punta Cana",
    destination: "Punta Cana, Rep. Dominicana",
    nights: 5,
    priceFrom: 2800,
    highlights: ["Resort 5 estrellas", "Actividades premium", "Spa y wellness", "Cena de premiación"],
    image: "/images/corp-puntacana.jpg",
    badge: "Top",
    includes: {
      flight: true,
      hotel: true,
      transfers: true,
      insurance: true,
      meals: true,
      activities: true,
    },
  },
  {
    id: "corp-8",
    category: "corporativo",
    title: "Convención Buenos Aires",
    destination: "Buenos Aires, Argentina",
    nights: 4,
    priceFrom: 1900,
    highlights: ["Hotel boutique Palermo", "Salones de eventos", "City tour cultural", "Cena show de tango"],
    image: "/images/corp-buenosaires.jpg",
    includes: {
      flight: true,
      hotel: true,
      transfers: true,
      insurance: true,
    },
  },
]

export const familyPackages: Package[] = [
  {
    id: "fam-1",
    category: "familiar",
    title: "Disney Orlando Mágico",
    destination: "Orlando, USA",
    nights: 7,
    priceFrom: 3500,
    highlights: ["Tickets a 4 parques Disney", "Hotel temático", "Desayuno con personajes", "Fast Pass incluido"],
    image: "/images/fam-orlando.jpg",
    badge: "Top",
    includes: {
      flight: true,
      hotel: true,
      transfers: true,
      insurance: true,
      activities: true,
    },
    description: "La aventura familiar perfecta en el mundo de Disney",
  },
  {
    id: "fam-2",
    category: "familiar",
    title: "Caribe All Inclusive",
    destination: "Riviera Maya, México",
    nights: 6,
    priceFrom: 2800,
    highlights: ["Resort familiar 5 estrellas", "Todo incluido premium", "Kids club y teens club", "Parque acuático"],
    image: "/images/fam-riviera.jpg",
    badge: "Promo",
    includes: {
      flight: true,
      hotel: true,
      transfers: true,
      insurance: true,
      meals: true,
      activities: true,
    },
  },
  {
    id: "fam-3",
    category: "familiar",
    title: "Aventura Bariloche",
    destination: "Bariloche, Argentina",
    nights: 5,
    priceFrom: 2200,
    highlights: ["Hotel con vista al lago", "Excursiones incluidas", "Cerro Catedral ski pass", "Chocolate tour"],
    image: "/images/fam-bariloche.jpg",
    includes: {
      flight: true,
      hotel: true,
      transfers: true,
      insurance: true,
      activities: true,
    },
  },
  {
    id: "fam-4",
    category: "familiar",
    title: "Playa del Carmen Relax",
    destination: "Playa del Carmen, México",
    nights: 7,
    priceFrom: 3100,
    highlights: ["Resort frente al mar", "All inclusive", "Excursión a Chichén Itzá", "Snorkel en cenotes"],
    image: "/images/fam-playacarmen.jpg",
    badge: "Nuevo",
    includes: {
      flight: true,
      hotel: true,
      transfers: true,
      insurance: true,
      meals: true,
      activities: true,
    },
  },
  {
    id: "fam-5",
    category: "familiar",
    title: "Europa Clásica",
    destination: "París, Londres, Roma",
    nights: 12,
    priceFrom: 5500,
    highlights: ["Hoteles céntricos", "Trenes entre ciudades", "Tours guiados", "Entradas a atracciones"],
    image: "/images/fam-europa.jpg",
    badge: "Top",
    includes: {
      flight: true,
      hotel: true,
      transfers: true,
      insurance: true,
    },
  },
  {
    id: "fam-6",
    category: "familiar",
    title: "Crucero Caribe",
    destination: "Caribe",
    nights: 8,
    priceFrom: 3800,
    highlights: ["Crucero 5 estrellas", "Todo incluido", "5 destinos caribeños", "Entretenimiento a bordo"],
    image: "/images/fam-crucero.jpg",
    includes: {
      flight: true,
      hotel: true,
      transfers: true,
      insurance: true,
      meals: true,
      activities: true,
    },
  },
  {
    id: "fam-7",
    category: "familiar",
    title: "Mendoza en Familia",
    destination: "Mendoza, Argentina",
    nights: 5,
    priceFrom: 1800,
    highlights: ["Cabañas familiares", "Tour por bodegas", "Rafting en el río", "Termas de Cacheuta"],
    image: "/images/fam-mendoza.jpg",
    includes: {
      flight: true,
      hotel: true,
      transfers: true,
      insurance: true,
      activities: true,
    },
  },
  {
    id: "fam-8",
    category: "familiar",
    title: "Brasil Playas",
    destination: "Florianópolis, Brasil",
    nights: 6,
    priceFrom: 2400,
    highlights: ["Resort frente al mar", "Media pensión", "Parque acuático", "Excursiones a islas"],
    image: "/images/fam-floripa.jpg",
    includes: {
      flight: true,
      hotel: true,
      transfers: true,
      insurance: true,
      meals: true,
      activities: true,
    },
  },
]

export const testimonials: Testimonial[] = [
  {
    id: "test-1",
    name: "María González",
    role: "Directora de RRHH",
    company: "TechCorp SA",
    quote:
      "Organizaron nuestro viaje de incentivos a Miami de manera impecable. El equipo quedó encantado y la experiencia superó todas nuestras expectativas.",
    rating: 5,
  },
  {
    id: "test-2",
    name: "Familia Rodríguez",
    role: "Clientes",
    quote:
      "Nuestras vacaciones en Disney fueron mágicas gracias a MC Creations. Todo estaba perfectamente coordinado y pudimos disfrutar sin preocupaciones.",
    rating: 5,
  },
  {
    id: "test-3",
    name: "Carlos Méndez",
    role: "CEO",
    company: "Innovatech",
    quote:
      "El retiro ejecutivo en Mendoza fue exactamente lo que necesitábamos. Excelente combinación de trabajo y relax en un entorno inspirador.",
    rating: 5,
  },
  {
    id: "test-4",
    name: "Familia Martínez",
    role: "Clientes",
    quote:
      "El crucero por el Caribe fue una experiencia inolvidable. La atención personalizada y el seguimiento durante todo el viaje fueron excepcionales.",
    rating: 5,
  },
]

export const faqs: FAQ[] = [
  {
    id: "faq-1",
    question: "¿Ofrecen planes de financiación?",
    answer:
      "Sí, trabajamos con diferentes opciones de financiación para que puedas disfrutar de tu viaje sin preocupaciones. Consultanos por las mejores tasas del mercado.",
  },
  {
    id: "faq-2",
    question: "¿Qué incluye el seguro de viaje?",
    answer:
      "Todos nuestros paquetes incluyen seguro de viaje con cobertura médica, cancelación, pérdida de equipaje y asistencia 24/7.",
  },
  {
    id: "faq-3",
    question: "¿Puedo personalizar un paquete?",
    answer:
      "Por supuesto. Todos nuestros paquetes son personalizables según tus necesidades y preferencias. Contactanos para armar tu viaje ideal.",
  },
  {
    id: "faq-4",
    question: "¿Cuánto tiempo antes debo reservar?",
    answer:
      "Recomendamos reservar con al menos 60 días de anticipación para obtener las mejores tarifas y disponibilidad, especialmente en temporada alta.",
  },
]
